### ISSUE TITLE
Where is the minimized version of the given java file?

### ISSUE THREAD

**Issue by jose** [sofiaoreis/lithium-slicer#8]
The running example states that

> ... the following command will minimize the file `GrayPaintScale.java` with respect to the test `testGetPaint` from D4J project `Chart`, bug number `24`.

but where is the minimized version of the `GrayPaintScale.java` placed?

**Comment by jose** [comment]
Is it in the `logs` directory?

I've just ran the running example as:

```
python3 run_lithium.py \
  --project Chart \
  --bug_number 24 \
  --test_case "org.jfree.chart.renderer.junit.GrayPaintScaleTests::testGetPaint" \
  --classes "source/org/jfree/chart/renderer/GrayPaintScale.java" \
  --expected_msg_path "java.lang.IllegalArgumentException: Color parameter outside of expected range: Red Green Blue" \
  --top 1
```

and got the following files

```
$ find logs_1 -type f
logs_1/Chart_24/24/GrayPaintScaleTests.testGetPaint/lithium_GrayPaintScale.java
logs_1/Chart_24/24/GrayPaintScaleTests.testGetPaint/GrayPaintScale.java
logs_1/Chart_24/24/GrayPaintScaleTests.testGetPaint/slicer-testGetPaint.json
logs_1/Chart_24/24/GrayPaintScaleTests.testGetPaint/uncomment_GrayPaintScale.java
logs_1/Chart_24/24/log-Chart-24b-Thu Oct  3 03:01:26 2024.log
```

- `GrayPaintScale.java` seems to be the original Java file.
- `uncomment_GrayPaintScale.java` seems to be original Java file but without comments.
- `lithium_GrayPaintScale.java` has exactly the same content as `uncomment_GrayPaintScale.java`.
- `slicer-testGetPaint.json` has the following content
```json
{
    "slicer": [
        {
            "class": "org/jfree/chart/renderer/GrayPaintScale.java",
            "loc": [
                1,
                2,
                3,
                4,
                5,

              171,
              172,
              173
            ]
        }
    ]
}
```

**Comment by sofiaoreis** [comment]
Yep, you're right. `lithium_GrayPaintScale.java` should be the minimized class. However, you won't see any changes in this case due to the issue reported in #9. If the class is not interesting, then minimization is not performed. 

Try running the example with the last pushed version of the tool. The expected minimization is at the end of the [Readme. md # Oracle Comparison] (https://github.com/sofiaoreis/lithium-slicer?tab=readme-ov-file#oracle-comparison) section. If you don't get the same minimization, let me know.

**Might be useful:** We remove lithium's temporary directory, but it may be useful to keep it if you want to get the entire test codebase. You will need to comment on the following line:

https://github.com/sofiaoreis/lithium-slicer/blob/eea85caf0df5688f24a1526b8cd0ea343534b698/app/run_lithium.py#L171
