### ISSUE TITLE
the original testcase is not interesting

### ISSUE THREAD

**Issue by jose** [sofiaoreis/lithium-slicer#9]
I've just ran the running example as:

```bash
python3 run_lithium.py \
  --project Chart \
  --bug_number 24 \
  --test_case "org.jfree.chart.renderer.junit.GrayPaintScaleTests::testGetPaint" \
  --classes "source/org/jfree/chart/renderer/GrayPaintScale.java" \
  --expected_msg_path "java.lang.IllegalArgumentException: Color parameter outside of expected range: Red Green Blue" \
  --top 1
```

and got the following:

```
Checking out 190 to /var/folders/42/jkmpchp95w3b_3kf4bngkrv00000gn/T/lithiu OK
Init local repository...................................................... OK
Tag post-fix revision...................................................... OK
Apply patch................................................................ OK
Run post-checkout hook..................................................... OK
Excluding broken/flaky tests............................................... OK
Excluding broken/flaky tests............................................... OK
Initialize fixed program version........................................... OK
Apply patch................................................................ OK
Initialize buggy program version........................................... OK
Diff 190:188............................................................... OK
Apply patch................................................................ OK
Tag pre-fix revision....................................................... OK
Check out program version: Chart-24b....................................... OK
Testcase type: line
The original testcase has 173 lines.
Checking that the original testcase is 'interesting'...
Lithium result: the original testcase is not 'interesting'!
  Tests performed: 1
  Test total: 173 lines
```

What does it mean `the original testcase is not 'interesting'!` ?

**Comment by jose** [comment]
Just found a log file that might help, not sure.

```
$ cat logs_1/Chart_24/24/log-Chart-24b-Thu\ Oct\ \ 3\ 03:01:26\ 2024.log

2024-10-03 03:01:26,540 - __main__ - INFO - Started Lithium-Slicer
2024-10-03 03:01:26,540 - __main__ - INFO - Running testcase GrayPaintScaleTests.testGetPaint from Chart-24b
2024-10-03 03:01:26,540 - __main__ - INFO - Files to minimize: ['GrayPaintScale.java']
2024-10-03 03:01:31,075 - __main__ - INFO - Minimizing GrayPaintScale.java
2024-10-03 03:01:31,075 - __main__ - INFO - Removing comments for GrayPaintScale.java
2024-10-03 03:01:31,626 - __main__ - INFO - Removing comments was finished for GrayPaintScale.java
2024-10-03 03:01:31,626 - __main__ - INFO - Running lithium for GrayPaintScale.java
2024-10-03 03:01:44,963 - __main__ - INFO - Lithium was finished for GrayPaintScale.java
2024-10-03 03:01:44,963 - __main__ - INFO - Copying minimized file to /private/tmp/lithium/lithium-slicer/app/logs_1/Chart_24/24
2024-10-03 03:01:44,970 - __main__ - INFO - The file GrayPaintScale.java was minimized in 0 minutes
2024-10-03 03:01:45,187 - __main__ - INFO - The testcase GrayPaintScaleTests.testGetPaint was finished in 0 minutes
```

**Comment by jose** [comment]
Also, my system's details:

```
$ uname -a
Darwin local 23.6.0 Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:15 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6031 arm64

$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)

$ python3 --version
Python 3.12.4

$ pip3 --version
pip 24.0 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)

$ perl -v
This is perl 5, version 34, subversion 1 (v5.34.1) built for darwin-thread-multi-2level
```

and I'm using [Defects4J v2.1.0](https://github.com/rjust/defects4j/tree/v2.1.0).

**Comment by sofiaoreis** [comment]
"not interesting" means lithium did not find any chunk of code to minimize in `org/jfree/chart/renderer/GrayPaintScale.java`, i.e., any chunk of code that, when removed, changed the expected test message.

**Comment by sofiaoreis** [comment]
Thanks for reporting! 

**The `README.md` was outdated.** In our first experiments, we used only the first line of the test message to attempt minimization. Then, we evolved to using part of the stack trace. Please see the new `README.md` file, where we describe the [oracle comparison heuristics](https://github.com/sofiaoreis/lithium-slicer?tab=readme-ov-file#oracle-comparison). We now support two different heuristics, but only the results of applying the first one were published at IJCAI. 

Instead of passing the first line of the message, you have to pass the file path to the failing test message/expected test message to the flag `--expected_msg_path`, which you can get from `defects4j`. The commands are also in the [README.md](https://github.com/sofiaoreis/lithium-slicer?tab=readme-ov-file#get-the-failing-test-message) file. The failing test message for Chart 24 is also available in our repo now.

> What does it mean the original testcase is not 'interesting'! ?

This means that Mozilla Lithium's attempted minimization will change the expected message of the test case, which we do NOT want. Therefore, Tandem-FL won't accept the minimization. But in your case, you get the test case is not "interesting" because the `compare_messages.py` expected a path for the failing test message, but instead, it got `java.lang.IllegalArgumentException: Color parameter outside of expected range: Red Green Blue` (as misled in the previous README.md). 

I pushed the last version of the tool (the one published at IJCAI), including a better version of the logs (that still needs a lot of work  #10). If you run it now, you will see the entire process, including lithium, attempting to minimize different chunks and the differences between the expected test message and the new test case message.
